propiedad/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
     path("web/",include('web.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from .views import index,registro,perfil,modificar_perfil,obtener_comunas,formulario_view,listar_propiedades_usuario
from .views import agregar_propiedad,borrar_propiedad,listar_propiedades,detalle_propiedad, PropiedadUpdateView

urlpatterns = [
   
    path("propiedades/", index, name= 'index'),
    path('registro/', registro, name='registro'),
    path('perfil/', perfil, name='perfil'),
    path('perfil/modificar/', modificar_perfil, name='modificar_perfil'),
    path('formulario/', formulario_view, name='formulario'),
    path('obtener_comunas/', obtener_comunas, name='obtener_comunas'),
    
    path('propiedades/agregar/', agregar_propiedad, name='agregar_propiedad'),
    path('propiedades/<int:pk>/editar/', PropiedadUpdateView.as_view(), name='editar_propiedad'),
    path('propiedades/<int:propiedad_id>/borrar/', borrar_propiedad, name='borrar_propiedad'),
    path('propiedades/usuario/', listar_propiedades_usuario, name='listar'),
    path('propiedades/<int:propiedad_id>/', detalle_propiedad, name='detalle_propiedad'),
    path("", listar_propiedades, name='listar_propiedades'),
    
    
    path('accounts/', include('django.contrib.auth.urls')),
   
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/forms.py
from django import forms
from .models import Usuario, Region, Comuna, Direccion,Propiedad,ImagenPropiedad,TipoPropiedad
from django.contrib.auth.forms import AuthenticationForm
from django.forms import formset_factory
from django.forms import inlineformset_factory

class UsuarioUpdateForm(forms.ModelForm):
    direccion_calle = forms.CharField(max_length=255)
    direccion_numero = forms.CharField(max_length=10)
    direccion_punto_referencia = forms.CharField(max_length=255, required=False)
    region = forms.ModelChoiceField(queryset=Region.objects.all(), empty_label="Seleccionar región")
    comuna = forms.ModelChoiceField(queryset=Comuna.objects.none(), empty_label="Seleccionar comuna")

    class Meta:
        model = Usuario
        fields = ['first_name', 'last_name', 'rut', 'email', 'telefono_personal', 'tipo_usuario', 'region', 'comuna', 'direccion_calle', 'direccion_numero', 'direccion_punto_referencia']
        labels = {
            'first_name': 'Nombre',
            'last_name': 'Apellido',
            'username': 'Nombre de usuario',
            'email': 'Correo electrónico',
            'telefono_personal': 'Teléfono',
            'region': 'Región',
            'comuna': 'Comuna',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        if self.instance and hasattr(self.instance, 'direccion') and self.instance.direccion:
            direccion = self.instance.direccion
            self.fields['direccion_calle'].initial = direccion.calle
            self.fields['direccion_numero'].initial = direccion.numero
            self.fields['direccion_punto_referencia'].initial = direccion.punto_referencia
            self.fields['region'].initial = direccion.comuna.region
            self.fields['comuna'].queryset = Comuna.objects.filter(region=direccion.comuna.region).order_by('nombre')
            self.fields['comuna'].initial = direccion.comuna
            
            # Agregar atributo personalizado al widget de 'comuna'
            self.fields['comuna'].widget.attrs['data-selected'] = direccion.comuna.id
        else:
            self.fields['comuna'].queryset = Comuna.objects.none()
        
        if 'data' in kwargs:
            data = kwargs['data']
            if 'region' in data:
                try:
                    region_id = int(data.get('region'))
                    self.fields['comuna'].queryset = Comuna.objects.filter(region_id=region_id).order_by('nombre')
                except (ValueError, TypeError):
                    self.fields['comuna'].queryset = Comuna.objects.none()

    def save(self, commit=True):
        usuario = super().save(commit=False)
        direccion_calle = self.cleaned_data['direccion_calle']
        direccion_numero = self.cleaned_data['direccion_numero']
        direccion_punto_referencia = self.cleaned_data['direccion_punto_referencia']
        region = self.cleaned_data['region']
        comuna = self.cleaned_data['comuna']

        direccion, created = Direccion.objects.get_or_create(
            calle=direccion_calle,
            numero=direccion_numero,
            punto_referencia=direccion_punto_referencia,
            comuna=comuna
        )

        usuario.direccion = direccion

        if commit:
            usuario.save()

        return usuario

class UsuarioForm(forms.ModelForm):
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmar contraseña', widget=forms.PasswordInput)
    region = forms.ModelChoiceField(queryset=Region.objects.all(), empty_label="Seleccionar región")
    comuna = forms.ModelChoiceField(queryset=Comuna.objects.none(), empty_label="Seleccionar comuna")
    
    class Meta:
        model = Usuario
        fields = ['first_name', 'last_name','username', 'rut', 'email', 'telefono_personal', 'region', 'comuna']
        labels = {
            'first_name':'Nombre',
            'last_name': 'Apellido',
            'username': 'Nombre de usuario',
            'email': 'Correo electrónico',
            'telefono_personal': 'Teléfono',
            'region': 'Región',
            'comuna': 'Comuna',
        }
        error_messages = {
            'username': {
                'unique': 'Ya existe un usuario con ese nombre de usuario. Por favor, elige otro.',
            }
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Cargar las regiones disponibles en el formulario
        self.fields['region'].queryset = Region.objects.all()

        # Si hay datos posteados (POST request), filtrar las comunas basadas en la región seleccionada
        if 'region' in self.data:
            try:
                region_id = int(self.data.get('region'))
                self.fields['comuna'].queryset = Comuna.objects.filter(region_id=region_id).order_by('nombre')
            except (ValueError, TypeError):
                pass  # Si hay algún error al intentar obtener el ID de la región, no se filtra nada
        
        # Si ya existe una instancia de usuario (estamos en una actualización), cargar las opciones seleccionadas
        elif self.instance.pk and self.instance.direccion and self.instance.direccion.comuna:
            self.fields['region'].initial = self.instance.direccion.comuna.region
            self.fields['comuna'].queryset = Comuna.objects.filter(region=self.instance.direccion.comuna.region).order_by('nombre')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        if commit:
            user.save()

            # Asignar la dirección al usuario si existe
            if 'region' in self.cleaned_data and 'comuna' in self.cleaned_data:
                region_id = self.cleaned_data['region'].id
                comuna_id = self.cleaned_data['comuna'].id
                direccion, created = Direccion.objects.get_or_create(
                    comuna_id=comuna_id,
                    defaults={
                        'calle': 'Sin especificar',
                        'numero': '10',
                        'punto_referencia': 'Sin especificar'
                    }
                )
                user.direccion = direccion
                user.save()

        return user


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Usuario'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Contraseña'})
    )



class ImagenForm(forms.ModelForm):
    class Meta:
        model = ImagenPropiedad
        fields = ['imagen', 'descripcion']
        
        
        
        # Define el formset fuera del formulario
ImagenFormSet = formset_factory(ImagenForm, extra=5)  # Permitir hasta 5 imágenes

class PropiedadForm(forms.ModelForm):
    # Campos para la dirección
    region = forms.ModelChoiceField(queryset=Region.objects.all(), empty_label="Seleccionar región")
    comuna = forms.ModelChoiceField(queryset=Comuna.objects.none(), empty_label="Seleccionar comuna")
    direccion_calle = forms.CharField(max_length=255)
    direccion_numero = forms.CharField(max_length=10)
    direccion_punto_referencia = forms.CharField(max_length=255, required=False)
    imagen_formset = ImagenFormSet()  # Instanciamos el formset aquí
    
    class Meta:
        model = Propiedad
        fields = ['nombre', 'descripcion', 'm2_construidos', 'm2_terreno', 'num_estacionamientos', 
                  'num_habitaciones', 'num_banos', 'tipo_propiedad', 'precio_mensual', 'region', 'comuna']
        labels = {
            'nombre': 'Nombre',
            'descripcion': 'Descripción',
            'm2_construidos': 'Metros Construidos',
            'm2_terreno': 'Metros de Terreno',
            'num_estacionamientos': 'Número de Estacionamientos',
            'num_habitaciones': 'Número de Habitaciones',
            'num_banos': 'Número de Baños',
            'tipo_propiedad': 'Tipo de Propiedad',
            'precio_mensual': 'Precio Mensual',
            'region': 'Región',
            'comuna': 'Comuna',
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.user = user  # Guardamos el usuario

        # Filtrar las comunas basadas en la región seleccionada si hay datos en la solicitud POST
        if 'region' in self.data:
            try:
                region_id = int(self.data.get('region'))
                self.fields['comuna'].queryset = Comuna.objects.filter(region_id=region_id).order_by('nombre')
            except (ValueError, TypeError):
                self.fields['comuna'].queryset = Comuna.objects.none()
        elif self.instance and self.instance.pk and self.instance.direccion and self.instance.direccion.comuna:
            direccion = self.instance.direccion
            self.fields['region'].initial = direccion.comuna.region
            self.fields['comuna'].queryset = Comuna.objects.filter(region=direccion.comuna.region).order_by('nombre')
            self.fields['comuna'].initial = direccion.comuna
            self.fields['direccion_calle'].initial = direccion.calle
            self.fields['direccion_numero'].initial = direccion.numero
            self.fields['direccion_punto_referencia'].initial = direccion.punto_referencia

    def save(self, commit=True):
        propiedad = super().save(commit=False)

        if self.user:
            propiedad.arrendador = self.user

        if commit:
            propiedad.save()

web/templates/propiedad/actualizar.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12 col-md-8 offset-md-2 mt-4 mb-4">
            <h3 class="text-center cafe_cuerpo">Actualizar Propiedad</h3>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}


                <div class="mb-3">
                    <h4 class="text-center">Imágenes</h4>
                    {{ formset.management_form }}
                    <div id="imagen_formset">
                        {% for form in formset %}
                        <div class="mb-3">
                            {{ form.as_p }}
                        </div>
                        {% endfor %}
                    </div>
                </div>

                <div class="text-center mb-5 d-flex justify-content-center gap-3">
                    <button type="submit" class="btn btn-primary">Actualizar Propiedad</button>
                    <a href="{% url 'detalle_propiedad' propiedad.id %}" class="btn btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const regionSelect = document.querySelector('select[name="region"]');
        const comunaSelect = document.querySelector('select[name="comuna"]');

        regionSelect.addEventListener('change', function () {
            const regionId = this.value;

            // Verificar que la región no esté vacía
            if (!regionId) {
                comunaSelect.innerHTML = '<option value="">Seleccionar comuna</option>';
                return;
            }

            fetch(`/obtener_comunas/?region=${regionId}`)
                .then(response => response.json())
                .then(data => {
                    // Vaciar el select de comunas
                    comunaSelect.innerHTML = '<option value="">Seleccionar comuna</option>';

                    // Llenar el select con las comunas obtenidas
                    data.comunas.forEach(comuna => {
                        const option = document.createElement('option');
                        option.value = comuna.id;
                        option.textContent = comuna.nombre;
                        comunaSelect.appendChild(option);
                    });
                })
                .catch(error => {
                    console.error('Error al obtener comunas:', error);
                });
        });
    });
</script>


{% endblock %}

web/templates/propiedad/agregar.html
{% extends 'base.html' %}

{% block content %}
<div class=" col-4 offset-4">
<h2>Agregar Nueva Propiedad</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <!-- Renderiza el formset management form -->
    {{ formset.management_form }}

    <!-- Renderiza los formularios del formset -->
    {% for form in formset %}
        <div class="formset-row">
            {{ form.as_p }}
        </div>
    {% endfor %}

    <div class="container-fluid mb-5">
    <button class="mb-5 btn btn-primary" type="submit">Guardar</button>
    </div>
</form>
</div>
<!-- Script JavaScript para manejar la carga dinámica de comunas -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#id_region').change(function () {
            var regionId = $(this).val();
            console.log("Region ID selected:", regionId); // Debug
            if (regionId) {
                $.ajax({
                    url: '{% url "obtener_comunas" %}', // Asegúrate de que esta línea sea correcta
                    data: {
                        'region_id': regionId
                    },
                    dataType: 'json',
                    success: function (data) {
                        console.log("Comunas data received:", data); // Debug
                        $('#id_comuna').empty();
                        $.each(data, function (index, comuna) {
                            $('#id_comuna').append('<option value="' + comuna.id +
                                '">' + comuna.nombre + '</option>');
                        });
                    },
                    error: function (xhr, status, error) {
                        console.log("Error en la solicitud AJAX:", error); // Debug
                    }
                });
            } else {
                $('#id_comuna').empty();
            }
        });
    });
</script>


{% endblock %}

web/templates/propiedad/detalle_propiedad.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<title>{{ propiedad.nombre }}</title>

<!-- Incluye los estilos en línea o en un archivo CSS separado -->
<style>
    .card-img-top {
        width: 100%;
        height: auto; /* Mantiene la altura proporcional basada en el ancho */
        object-fit: cover; /* Asegura que la imagen cubra el contenedor sin distorsionarse */
    }
    .image-gallery {
        display: flex;
        flex-wrap: wrap;
        gap: 10px; /* Espacio entre las imágenes */
    }
    .image-item {
        flex: 1 1 calc(33.333% - 10px); /* Tres imágenes por fila, ajusta según el diseño */
        box-sizing: border-box;
        margin-bottom: 10px;
    }
    .image-item img {
        width: 100%;
        height: auto;
        max-height: 200px;
        object-fit: cover;
    }
    .image-description {
        text-align: center;
        margin-top: 5px;
    }
    .btn-custom {
        margin-right: 10px;
    }
    .btn-secondary {
        background-color: #6c757d;
        border-color: #6c757d;
    }
    .btn-secondary:hover {
        background-color: #5a6268;
        border-color: #545b62;
    }
</style>

<div class="container mt-4">
    <div class="card mb-4">
        <!-- Imagen principal -->
        {% if propiedad.imagenes.first %}
            <img src="{{ propiedad.imagenes.first.imagen.url }}" class="card-img-top" alt="{{ propiedad.nombre }}">
        {% else %}
            <img src="{% static 'default.jpg' %}" class="card-img-top" alt="Imagen no disponible">
        {% endif %}

        <div class="card-body">
            <h5 class="card-title">{{ propiedad.nombre|title }}</h5>
            <p><strong>Descripción:</strong> {{ propiedad.descripcion }}</p>
            <p><strong>Metros Construidos:</strong> {{ propiedad.m2_construidos }}</p>
            <p><strong>Metros de Terreno:</strong> {{ propiedad.m2_terreno }}</p>
            <p><strong>Número de Estacionamientos:</strong> {{ propiedad.num_estacionamientos }}</p>
            <p><strong>Número de Habitaciones:</strong> {{ propiedad.num_habitaciones }}</p>
            <p><strong>Número de Baños:</strong> {{ propiedad.num_banos }}</p>
            <p><strong>Tipo de Propiedad:</strong> {{ propiedad.tipo_propiedad.nombre_tipo }}</p>
            <p><strong>Precio Mensual:</strong> ${{ propiedad.precio_mensual }}</p>
            <p><strong>Región:</strong> {{ propiedad.direccion.comuna.region }}</p>
            <p><strong>Comuna:</strong> {{ propiedad.direccion.comuna }}</p>
            <p><strong>Dirección Calle:</strong> {{ propiedad.direccion.calle }}</p>
            <p><strong>Dirección Número:</strong> {{ propiedad.direccion.numero }}</p>
            <p><strong>Dirección Punto Referencia:</strong> {{ propiedad.direccion.punto_referencia }}</p>

            <!-- Galería de Imágenes -->
            <h6 class="mt-4">Galería de Imágenes</h6>
            <div class="image-gallery">
                {% for imagen in propiedad.imagenes.all %}
                    <div class="image-item">
                        <img src="{{ imagen.imagen.url }}" alt="{{ imagen.descripcion }}">
                        <div class="image-description">{{ imagen.descripcion }}</div>
                    </div>
                {% empty %}
                    <p>No hay imágenes disponibles.</p>
                {% endfor %}
            </div>

            <!-- Botones de acción -->
            <div class="mt-3">
                {% if user == propiedad.arrendador %}
                    <a href="{% url 'editar_propiedad' propiedad.id %}" class="btn btn-warning btn-custom">Actualizar Propiedad</a>
                    <a href="{% url 'borrar_propiedad' propiedad.id %}" class="btn btn-danger btn-custom">Eliminar Propiedad</a>
                {% endif %}
                <a href="{% url 'listar_propiedades' %}" class="btn btn-secondary">Volver</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

web/templates/propiedad/eliminar.html
{% extends 'base.html' %}

{% block content %}
<h1>Eliminar Propiedad: {{ propiedad.nombre }}</h1>

<p>¿Estás seguro de que deseas eliminar esta propiedad?</p>

<form method="post">
    {% csrf_token %}
    <button type="submit">Eliminar</button>
</form>

<a href="{% url 'detalle_propiedad' propiedad.id %}">Cancelar</a>
{% endblock %}

web/templates/propiedad/listar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Mis Propiedades</h1>

    <!-- Mostrar el número total de propiedades -->
    <p>Se encontraron {{ total_propiedades }} propiedades.</p>

    <!-- Mostrar propiedades -->
    <div class="row">
        {% for propiedad in page_obj %}
            <div class="col-md-6 col-lg-4 mb-4">
                <div class="card shadow-sm">
                    {% if propiedad.imagenes.first %}
                        <img src="{{ propiedad.imagenes.first.imagen.url }}" class="card-img-top" width="30%" alt="{{ propiedad.nombre }}">
                    {% else %}
                        <img src="{% static 'img/logo.jpg' %}" class="card-img-top" alt="Imagen no disponible">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ propiedad.nombre|title }}</h5>
                        <p class="card-text">
                            <strong>Tipo:</strong> {{ propiedad.tipo_propiedad.nombre_tipo }}<br>
                            <strong>Precio:</strong> ${{ propiedad.precio_mensual }}<br>
                            <strong>M2 Terreno:</strong> {{ propiedad.m2_terreno }}
                        </p>
                        <a href="{% url 'detalle_propiedad' propiedad.id %}" class="btn btn-primary">Ver Detalles</a>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>No tienes propiedades registradas.</p>
        {% endfor %}
    </div>

    <!-- Controles de Paginación -->
    <nav aria-label="Page navigation" class="mt-4">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="First">
                        <span aria-hidden="true">&laquo;&laquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                <li class="page-item {% if num == page_obj.number %}active{% endif %}">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                        <span aria-hidden="true">&raquo;&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}

web/templates/propiedad/listar_propiedades.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="container-fluid my-4 py-4">
    <div class="row">
        <!-- Barra Lateral de Filtro -->
        <div class="col-md-3">
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="mb-3">Filtrar Propiedades</h2>
                    <form method="GET" action="{% url 'listar_propiedades' %}">
                        {% csrf_token %}
                        <div class="mb-3">
                            {{ form|crispy }}
                        </div>
                        <button type="submit" class="btn btn-primary">Filtrar</button>
                    </form>
                </div>
            </div>
        </div>

        <!-- Resultados -->
        <div class="col-md-9">
            <div class="container-fluid text-center d-flex justify-content-center align-items-center">
                <h1 class="mb-4 ">Listado de Propiedades</h1>
            </div>

            <div class="row mb-4">
                <div class="col-md-12">
                    {% if total_propiedades is not None %}
                    <p>Se encontraron {{ total_propiedades }} propiedades.</p>
                    {% else %}
                    <p>No se encontraron propiedades.</p>
                    {% endif %}
                </div>
            </div>

            <div class="row">
                {% if page_obj.object_list %}
                <div class="col-md-12">
                    <h2 class="mb-4">Resultados:</h2>
                    <div class="row">
                        {% for propiedad in page_obj %}
                        <div class="col-md-4 col-lg-3 mb-4">
                            <div class="card shadow-sm d-flex flex-column">
                                {% if propiedad.imagenes.first %}
                                <img src="{{ propiedad.imagenes.first.imagen.url }}" class="card-img-top"
                                    alt="{{ propiedad.nombre }}" style="object-fit: cover;">
                                {% else %}
                                <img src="{% static 'img/logo.jpg' %}" class="card-img-top" alt="Imagen no disponible"
                                    style="object-fit: cover;">
                                {% endif %}
                                <div class="card-body d-flex flex-column">
                                    <h5 class="card-title">{{ propiedad.nombre|title }}</h5>
                                    <p class="card-text">
                                        <strong>Tipo:</strong> {{ propiedad.tipo_propiedad.nombre_tipo }}<br>
                                        <strong>Precio:</strong> ${{ propiedad.precio_mensual }}<br>
                                        <strong>M2 Terreno:</strong> {{ propiedad.m2_terreno }}
                                    </p>
                                    <a href="{% url 'detalle_propiedad' propiedad.id %}"
                                        class="btn btn-primary mt-auto">Ver Detalles</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                    <!-- Controles de Paginación -->
                    <nav aria-label="Page navigation" class="mt-4">
                        <ul class="pagination justify-content-center">
                            {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page=1" aria-label="First">
                                    <span aria-hidden="true">&laquo;&laquo;</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                    aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                            {% endif %}

                            {% for num in page_obj.paginator.page_range %}
                            <li class="page-item {% if num == page_obj.number %}active{% endif %}">
                                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                            </li>
                            {% endfor %}

                            {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                                    <span aria-hidden="true">&raquo;&raquo;</span>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
                {% else %}
                <div class="container-fluid my-4 py-4">
                    
                    <div class="my-4">
                        <p class="text-center">No se encontraron propiedades.</p>
                    </div>
                </div>
                  
                {% endif %}
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#id_region').change(function () {
            var regionId = $(this).val();
            console.log("Region ID selected:", regionId); // Debug
            $('#id_comuna').empty().append('<option value="">Seleccionar comuna</option>');
            if (regionId) {
                $.ajax({
                    url: '{% url "obtener_comunas" %}', // Asegúrate de que esta línea sea correcta
                    data: {
                        'region_id': regionId
                    },
                    dataType: 'json',
                    success: function (data) {
                        console.log("Comunas data received:", data); // Debug
                        $.each(data, function (index, comuna) {
                            $('#id_comuna').append('<option value="' + comuna.id +
                                '">' + comuna.nombre + '</option>');
                        });
                    },
                    error: function (xhr, status, error) {
                        console.log("Error en la solicitud AJAX:", error); // Debug
                    }
                });
            }
        });
    });
</script>
{% endblock %}